version: '3.8'

services:
  app:
    container_name: innoshop_app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - /var/www/vendor
    environment:
      - DB_HOST=db
      - DB_DATABASE=innoshop
      - DB_USERNAME=raidenei
      - DB_PASSWORD=akusayangei
    depends_on:
      - db
    networks:
      - innoshop-network
    # Removed the "command" line to allow PHP-FPM to start as default
    expose:
      - "9000"  # Exposing PHP-FPM port for internal network access

  webserver:
    image: nginx:alpine
    container_name: innoshop_webserver
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d  # Ensure `default.conf` is here
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - innoshop-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: innoshop_db
    environment:
      MYSQL_ROOT_PASSWORD: dafasayangei
      MYSQL_DATABASE: innoshop
      MYSQL_USER: raidenei
      MYSQL_PASSWORD: akusayangei
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - innoshop-network

networks:
  innoshop-network:
    driver: bridge

volumes:
  db_data:
